version: '3.3'

services:
  app:
    build: .
    container_name: blog-api-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_NAME: blog_db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_DIALECT: mysql
      PORT: 3000
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8
    container_name: blog-api-db
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_db
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
